***
 a = 0, b=0, c=1 are the 1st three terms. All other terms in the Lucas sequence are generated by the sum of their 3 most recent predecessors. Write a program to generate the first n terms of a Lucas Sequence.
Input format:
The input containing an integer 'n' which denotes the given number
Output format:
Print the  'n' terms of the Lucas Sequence, separated by a single space. There are no leading or trailing spaces in the output.
Refer the sample output for formatting.
Sample Input:
5
Sample Output:
0 0 1 1 2

***
def generate_lucas_sequence(n):
    # Initialize the first three terms
    if n == 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 0]
    elif n == 3:
        return [0, 0, 1]

    sequence = [0, 0, 1]

    # Generate the sequence up to n terms
    for i in range(3, n):
        next_term = sequence[i - 1] + sequence[i - 2] + sequence[i - 3]
        sequence.append(next_term)

    return sequence

# Input reading
n = int(input().strip())

# Generate the Lucas sequence
lucas_sequence = generate_lucas_sequence(n)

# Output result
print(" ".join(map(str, lucas_sequence)))
